title: First Use of Jekyll
author: JHBlack
email: jhblack25@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 This is my first use of Jekyll on Github. I'm learning how to use web development more proficiently through Microsoft's 'Web Development For Beginners" repository. 
 I don't have a twitter anymore :( Here's my github though. Follow my profile!

# social links
twitter_username: none
github_username:  JHBlack

show_excerpts: true # set to false to remove excerpts on the homepage
